### ISSUE TITLE
implement GameStats Service

### ISSUE THREAD

**Issue by Muhannes** [Muhannes/d7038e#12]
Keeps track of the states of players and the game.

Should be responsible for taking trapPlacements requests from clients.
Listens for collision from Physics service and decides if any event should occur (Player died, etc.)
decides when game is over.
more? just comment

**Comment by Muhannes** [comment]
Started, but put on hold, since it depends on other stuff

**Comment by tedjoh-2** [comment]
Will be functional with new push for players ability to put down traps (in a initial form of box).

**Comment by tedjoh-2** [comment]
This issue is done for now
