### ISSUE TITLE
Movement skipping

### ISSUE THREAD

**Issue by tedjoh-2** [Muhannes/d7038e#16]
When two players are in the same game, they see each other skipping, moving a direction but also *lagging* to the opposite direction. There must be something wrong with how the server either sends out the direction or how the button press sends to the server.

Also, at the moment, the server does react accordingly to stop movement (i.e. when a player stops pressing down a-w-s-d, the player should stand still), the player continues to walk a direction..

**Comment by Muhannes** [comment]
took another approach, but this works now. a bit laggy without linear convergence though.
