### ISSUE TITLE
Area of Interest

### ISSUE THREAD

**Issue by tedjoh-2** [Muhannes/d7038e#17]
The idea : 

The map is divided into smaller regions, where each region has an id. Whenever a player is walking around, he is within a certain region and thus the server will know that if a player is walking in region '1', the server will send "footsteps" to all the players in the same region. 

Player (R.1) -> Server -> Broadcast to all players in R.1

An extension to this is to provide that when a monster walks, it is heard all around the map with different sound levels. Same goes with when a player dies, when a trap is created and so on.

**Comment by TrulsHaraldsson** [comment]
Area of Interest functions are now implemented. However, integration with the update loop on server side is not done.
