### ISSUE TITLE
Creating lobby room with same name

### ISSUE THREAD

**Issue by TrulsHaraldsson** [Muhannes/d7038e#2]
How to recreate the bug:
Start two clients A and B.
Client A creates a room with name "test"
Client B creates a room with name "test"
They won't join the same room.

**Comment by tedjoh-2** [comment]
Verkar det ens rimligt att rum kan ha samma namn? Borde väl vara en begränsning.

**Comment by tedjoh-2** [comment]
Men jag förstår tanken, Valet är väl, att gå på ID för rummet eller så ändrar man så att man tar ut från servern vilka banor som finns vid namn och om det redan finns måste man välja annat.

**Comment by TrulsHaraldsson** [comment]
Fixed
