### ISSUE TITLE
Joining

### ISSUE THREAD

**Issue by tedjoh-2** [Muhannes/d7038e#35]
Story : 
A player makes a game called *game*, he joins it and waits for others.

Another player "loggs in" and sees the game called *game* but has also typed in the same name, as he originally intended to create one named just that. He joins the first players game instead of creating a new, however how when he joins, there will be 5 players in the lobby (p1, p2, p1, p2, p2) for player 2, and (p1, p2 ,p2) for player 1 ( the creator).

**Comment by Muhannes** [comment]
fixed
