### ISSUE TITLE
Return from lobby error

### ISSUE THREAD

**Issue by Muhannes** [Muhannes/d7038e#7]
When atleast 2 people is in lobby, and one leaves, there is a null pointer exception. The player trying to leave is sent back to a empty lobby.

**Comment by TrulsHaraldsson** [comment]
This is fixed now. Client received notifications from lobby server even though it left a lobby. This triggered code in gamelobby state that led to a nullpointer exception. The solution was to remove gamelobby state as listener to clientlobbyservice before sending leave() message to server.
